# typed: false
# frozen_string_literal: true

# Homebrew formula for the babysit CLI (`bbs`).
#
# Delivers the compiled `bbs` multicall binary. All core bins are now Go,
# reachable as `bbs <sub>` (ticket, config, secrets, upgrade, design,
# dashboard, autopilot, foreman), plus the `bbs-config` / `bbs-env` argv0
# aliases. It does NOT install the
# babysit skill pack (skills, workflows, DESIGN.md/CSV data), which
# comes from git clone + bin/setup-skills.
#
# Generated by scripts/gen-formula.sh; the release workflow regenerates it with
# real checksums on each tag. Do not hand-edit the sha256 values.
class Bbs < Formula
  desc "Babysit CLI — Go multicall for config, env, slug, ticket, and more"
  homepage "https://github.com/lohi-ai/babysit"
  version "1.88.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_darwin_arm64.tar.gz"
      sha256 "7fba73f6a1b08f9701163ee2e58df46cfec2398921f711085da4f61675aa0b6d"
    end
    on_intel do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_darwin_amd64.tar.gz"
      sha256 "e09266553f758535fbe2855fcca83ab56712a14764763a50eb5ecf0007bd3310"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_linux_arm64.tar.gz"
      sha256 "a81c27b116132fe1603fcd48ff2291b189872c6e4caa77e6dca0155e8014b452"
    end
    on_intel do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_linux_amd64.tar.gz"
      sha256 "c5f6f208eef62407382391177c5b296871729466d9f7c7662d3b55d023e73154"
    end
  end

  def install
    bin.install "bbs"
    # Multicall aliases: dispatch keys on argv0, so bbs-<name> runs "bbs <name>".
    # Only subcommands the CLI registers today are aliased.
    bin.install_symlink bin/"bbs" => "bbs-config"
    bin.install_symlink bin/"bbs" => "bbs-env"
  end

  test do
    assert_match "babysit CLI", shell_output("#{bin}/bbs --help")
    assert_match "config", shell_output("#{bin}/bbs-config --help")
  end
end
