# typed: false
# frozen_string_literal: true

# Homebrew formula for the babysit CLI (`bbs`).
#
# Delivers the compiled `bbs` multicall binary. All core bins are now Go,
# reachable as `bbs <sub>` (ticket, config, secrets, upgrade, design,
# dashboard, autopilot, foreman), plus the `bbs-config` / `bbs-env` argv0
# aliases. It does NOT install the
# babysit skill pack (skills, workflows, DESIGN.md/CSV data), which
# comes from git clone + bin/setup-skills.
#
# Generated by scripts/gen-formula.sh; the release workflow regenerates it with
# real checksums on each tag. Do not hand-edit the sha256 values.
class Bbs < Formula
  desc "Babysit CLI — Go multicall for config, env, slug, ticket, and more"
  homepage "https://github.com/lohi-ai/babysit"
  version "1.93.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_darwin_arm64.tar.gz"
      sha256 "0305898df9a7f5a4167640b064d10f8cc58a839d93eb3d045a79411f79dafad8"
    end
    on_intel do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_darwin_amd64.tar.gz"
      sha256 "e9df4b7e62d4452ae65020ae4af4c83057a31347f1bf96f4c1fb214e52b2dc24"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_linux_arm64.tar.gz"
      sha256 "b65c30e38d39c91828615d483f43e97fed71a558a270c42dcb8fd6f776c8ab86"
    end
    on_intel do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_linux_amd64.tar.gz"
      sha256 "ae9cf90af3521d04c80ac0ce10d77ad593bae7ab595ee88d52e88ddc84a581af"
    end
  end

  def install
    bin.install "bbs"
    # Multicall aliases: dispatch keys on argv0, so bbs-<name> runs "bbs <name>".
    # Only subcommands the CLI registers today are aliased.
    bin.install_symlink bin/"bbs" => "bbs-config"
    bin.install_symlink bin/"bbs" => "bbs-env"
  end

  test do
    assert_match "babysit CLI", shell_output("#{bin}/bbs --help")
    assert_match "config", shell_output("#{bin}/bbs-config --help")
  end
end
