#!/usr/bin/env bash
# gen-formula.sh — emit Formula/bbs.rb for a given version + checksums.
#
# Single source of truth for the Homebrew formula shape. The committed
# Formula/bbs.rb is this script's output with placeholder (all-zero) checksums;
# the release workflow re-runs it against goreleaser's real dist/checksums.txt
# on tag, so the tap always carries verified checksums.
#
# Usage:
#   scripts/gen-formula.sh <version> [checksums.txt]   # writes to stdout
#
# <version>        bare version, e.g. 1.55.20 (no leading v)
# [checksums.txt]  goreleaser checksum file; omit to emit all-zero placeholders.
#                  Format per line: "<sha256>  bbs_<ver>_<os>_<arch>.tar.gz"
set -euo pipefail

VERSION="${1:?usage: gen-formula.sh <version> [checksums.txt]}"
SUMS="${2:-}"
ZERO="0000000000000000000000000000000000000000000000000000000000000000"

# sha256 for a given os_arch suffix; placeholder when no checksum file given.
sum_for() {
  local suffix="$1"
  [ -n "$SUMS" ] || { printf '%s' "$ZERO"; return; }
  local line
  line="$(grep "_${suffix}.tar.gz$" "$SUMS" || true)"
  [ -n "$line" ] || { echo "gen-formula: no checksum for _${suffix}.tar.gz in $SUMS" >&2; exit 1; }
  printf '%s' "${line%% *}"
}

DARWIN_ARM64="$(sum_for darwin_arm64)"
DARWIN_AMD64="$(sum_for darwin_amd64)"
LINUX_ARM64="$(sum_for linux_arm64)"
LINUX_AMD64="$(sum_for linux_amd64)"

cat <<RUBY
# typed: false
# frozen_string_literal: true

# Homebrew formula for the babysit CLI (\`bbs\`).
#
# Delivers the compiled \`bbs\` multicall binary: subcommands \`config\` and
# \`env\` today, plus the \`bbs-config\` / \`bbs-env\` aliases. It does NOT install
# the babysit skill pack or the bash bins — those come from git clone +
# bin/setup-skills (see the project README).
#
# Generated by scripts/gen-formula.sh; the release workflow regenerates it with
# real checksums on each tag. Do not hand-edit the sha256 values.
class Bbs < Formula
  desc "Babysit CLI — config and env subcommands today"
  homepage "https://github.com/lohi-ai/babysit"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_darwin_arm64.tar.gz"
      sha256 "${DARWIN_ARM64}"
    end
    on_intel do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_darwin_amd64.tar.gz"
      sha256 "${DARWIN_AMD64}"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_linux_arm64.tar.gz"
      sha256 "${LINUX_ARM64}"
    end
    on_intel do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_linux_amd64.tar.gz"
      sha256 "${LINUX_AMD64}"
    end
  end

  def install
    bin.install "bbs"
    # Multicall aliases: dispatch keys on argv0, so bbs-<name> runs "bbs <name>".
    # Only subcommands the CLI registers today are aliased.
    bin.install_symlink bin/"bbs" => "bbs-config"
    bin.install_symlink bin/"bbs" => "bbs-env"
  end

  test do
    assert_match "babysit CLI", shell_output("#{bin}/bbs --help")
    assert_match "config", shell_output("#{bin}/bbs-config --help")
  end
end
RUBY
