import { useEffect, useMemo, useState } from 'react';
import { loadSnapshot, type LoadedSnapshot } from './lib/data';
import { FilterProvider } from './contexts/FilterContext';
import { Layout } from './components/Layout';
import { ErrorBox } from './components/ErrorBox';
import { Home } from './views/Home';
import { TicketsList } from './views/TicketsList';
import { TicketDetail } from './views/TicketDetail';
import { Timeline } from './views/Timeline';
import { Analytics } from './views/Analytics';
import { LiveStatus } from './views/LiveStatus';
import { DecisionsFeed } from './views/DecisionsFeed';
import { SkillEvents } from './views/SkillEvents';

function useHashRoute(): string {
  const [hash, setHash] = useState<string>(() => {
    // Default landing route is #/
    if (!window.location.hash || window.location.hash === '#') {
      history.replaceState(null, '', '#/');
      return '#/';
    }
    return window.location.hash;
  });
  useEffect(() => {
    const h = () => setHash(window.location.hash || '#/');
    window.addEventListener('hashchange', h);
    return () => window.removeEventListener('hashchange', h);
  }, []);
  return hash;
}

function matchTicketDetail(hash: string): string | null {
  const m = /^#\/tickets\/([^/?#]+)/.exec(hash);
  return m ? m[1] : null;
}

function AppInner({ snapshot, hash }: { snapshot: LoadedSnapshot; hash: string }) {
  const ticketId = matchTicketDetail(hash);
  const route = hash.split('?')[0]; // strip query for route matching

  let view;
  if (route === '#/' || route === '' || route === '#') view = <Home snapshot={snapshot} />;
  else if (route === '#/tickets') view = <TicketsList snapshot={snapshot} />;
  else if (ticketId) view = <TicketDetail snapshot={snapshot} ticketId={ticketId} />;
  else if (route === '#/timeline') view = <Timeline snapshot={snapshot} />;
  else if (route === '#/analytics') view = <Analytics snapshot={snapshot} />;
  else if (route === '#/live') view = <LiveStatus snapshot={snapshot} />;
  else if (route === '#/decisions') view = <DecisionsFeed snapshot={snapshot} />;
  else if (route === '#/skill-events') view = <SkillEvents snapshot={snapshot} />;
  else {
    const safeHash = hash.length > 80 ? hash.slice(0, 80) + '…' : hash;
    view = <ErrorBox title="Not found" body={`No route for ${safeHash}`} />;
  }

  return (
    <>
      {snapshot._stale && (
        <div
          className="fixed top-0 left-0 right-0 z-50 px-4 py-2 text-sm"
          style={{
            backgroundColor: 'var(--status-started-bg)',
            color: 'var(--status-started-text)',
            borderBottom: '1px solid var(--border-emphasis)',
          }}
        >
          This dashboard was generated by babysit pre-v2 — re-run{' '}
          <code className="font-mono">bbs-dashboard</code> to see decisions, skill events, and live status.
        </div>
      )}
      <Layout meta={snapshot.meta} snapshot={snapshot} active={hash}>
        <div key={route} className="motion-safe:animate-fade-in">{view}</div>
      </Layout>
    </>
  );
}

export function App() {
  const hash = useHashRoute();
  const snapshot = useMemo<LoadedSnapshot | null>(() => {
    try {
      return loadSnapshot();
    } catch {
      return null;
    }
  }, []);

  if (!snapshot) {
    return (
      <Layout meta={null} active={hash}>
        <ErrorBox
          title="Snapshot not loaded"
          body="data.js is missing or corrupt. Run `bbs-dashboard` (or `bbs-dashboard --no-open`) from the babysit repo to refresh it."
        />
      </Layout>
    );
  }

  return (
    <FilterProvider activeProject={snapshot.meta.active_project}>
      <AppInner snapshot={snapshot} hash={hash} />
    </FilterProvider>
  );
}
