import { useEffect, useState } from 'react';
import { type LoadedSnapshot } from './lib/data';
import { useSnapshot } from './lib/useSnapshot';
import { FilterProvider } from './contexts/FilterContext';
import { ControlProvider } from './contexts/ControlContext';
import { Layout } from './components/Layout';
import { ErrorBox } from './components/ErrorBox';
import { Home } from './views/Home';
import { TicketsList } from './views/TicketsList';
import { TicketDetail } from './views/TicketDetail';
import { Timeline } from './views/Timeline';
import { Analytics } from './views/Analytics';
import { LiveStatus } from './views/LiveStatus';
import { Foremen } from './views/Foremen';
import { DecisionsFeed } from './views/DecisionsFeed';
import { SkillEvents } from './views/SkillEvents';

function useHashRoute(): string {
  const [hash, setHash] = useState<string>(() => {
    // Default landing route is #/
    if (!window.location.hash || window.location.hash === '#') {
      history.replaceState(null, '', '#/');
      return '#/';
    }
    return window.location.hash;
  });
  useEffect(() => {
    const h = () => setHash(window.location.hash || '#/');
    window.addEventListener('hashchange', h);
    return () => window.removeEventListener('hashchange', h);
  }, []);
  return hash;
}

function matchTicketDetail(hash: string): string | null {
  const m = /^#\/tickets\/([^/?#]+)/.exec(hash);
  return m ? m[1] : null;
}

function AppInner({ snapshot, hash, error, retry }: { snapshot: LoadedSnapshot; hash: string; error: string | null; retry: () => void }) {
  const ticketId = matchTicketDetail(hash);
  const route = hash.split('?')[0]; // strip query for route matching

  let view;
  if (route === '#/' || route === '' || route === '#') view = <Home snapshot={snapshot} />;
  else if (route === '#/tickets') view = <TicketsList snapshot={snapshot} />;
  else if (ticketId) view = <TicketDetail snapshot={snapshot} ticketId={ticketId} />;
  else if (route === '#/timeline') view = <Timeline snapshot={snapshot} />;
  else if (route === '#/analytics') view = <Analytics snapshot={snapshot} />;
  else if (route === '#/live') view = <LiveStatus snapshot={snapshot} />;
  else if (route === '#/foremen') view = <Foremen snapshot={snapshot} />;
  else if (route === '#/decisions') view = <DecisionsFeed snapshot={snapshot} />;
  else if (route === '#/skill-events') view = <SkillEvents snapshot={snapshot} />;
  else {
    const safeHash = hash.length > 80 ? hash.slice(0, 80) + '…' : hash;
    view = <ErrorBox title="Not found" body={`No route for ${safeHash}`} />;
  }

  return (
    <>
      {error && (
        // A poll that fails once we already have data: what is on screen is
        // still real, just frozen at the last successful read. Say that rather
        // than replacing the dashboard with an error page.
        <div
          className="fixed top-0 left-0 right-0 z-50 px-4 py-2 text-sm"
          style={{
            backgroundColor: 'var(--status-blocked-bg)',
            color: 'var(--status-blocked-text)',
            borderBottom: '1px solid var(--border-emphasis)',
          }}
        >
          <span>Lost connection to the dashboard server — showing the last data received. ({error})</span>
          <button
            type="button"
            onClick={retry}
            className="ml-3 underline"
            style={{ color: 'inherit' }}
          >
            Retry
          </button>
        </div>
      )}
      {snapshot._stale && (
        <div
          className="fixed top-0 left-0 right-0 z-50 px-4 py-2 text-sm"
          style={{
            backgroundColor: 'var(--status-started-bg)',
            color: 'var(--status-started-text)',
            borderBottom: '1px solid var(--border-emphasis)',
          }}
        >
          This dashboard was generated by babysit pre-v2 — re-run{' '}
          <code className="font-mono">bbs-dashboard</code> to see decisions, skill events, and live status.
        </div>
      )}
      <Layout meta={snapshot.meta} snapshot={snapshot} active={hash}>
        <div key={route} className="motion-safe:animate-fade-in">{view}</div>
      </Layout>
    </>
  );
}

export function App() {
  const hash = useHashRoute();
  const { snapshot, loading, error, source, refresh } = useSnapshot();

  // Served mode is async: the first paint happens before any data exists. The
  // views all index into the snapshot at render, so they cannot run yet.
  if (!snapshot && loading) {
    return (
      <Layout meta={null} active={hash}>
        <div className="p-6 text-sm" style={{ color: 'var(--text-tertiary)' }}>
          Loading babysit state…
        </div>
      </Layout>
    );
  }

  if (!snapshot) {
    return (
      <Layout meta={null} active={hash}>
        <ErrorBox
          title={source === 'server' ? 'Cannot reach the dashboard server' : 'Snapshot not loaded'}
          body={
            source === 'server'
              ? `GET /api/snapshot failed${error ? `: ${error}` : ''}. The server that served this page is gone — restart it with \`bbs dashboard\`.`
              : 'data.js is missing or corrupt. Run `bbs dashboard --snapshot` from the babysit repo to refresh it.'
          }
        />
      </Layout>
    );
  }

  return (
    <FilterProvider activeProject={snapshot.meta.active_project}>
      <ControlProvider source={source} error={error} refresh={refresh}>
        <AppInner snapshot={snapshot} hash={hash} error={error} retry={refresh} />
      </ControlProvider>
    </FilterProvider>
  );
}
